---
- name: Completely Disable Firewall for Lab Environment
  community.windows.win_firewall:
    state: disabled
    profiles:
      - Domain
      - Private
      - Public

#- name: Set Network Profile to Private
#  ansible.windows.win_shell: |
#    $Profile = Get-NetConnectionProfile
#    if ($Profile.NetworkCategory -ne 'Private') {
#        Set-NetConnectionProfile -NetworkCategory Private
#    }
#  register: profile_change
#  changed_when: profile_change.stdout != ""

- name: Enable RDP & Disable NLA (Registry)
  ansible.windows.win_regedit:
    path: "{{ item.path }}"
    name: "{{ item.name }}"
    data: 0
    type: dword
  loop:
    - { path: 'HKLM:\System\CurrentControlSet\Control\Terminal Server', name: 'fDenyTSConnections' }
    - { path: 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp', name: 'UserAuthentication' }

- name: Allow Ping (ICMP) - This fixes your "Cannot Ping" issue
  community.windows.win_firewall_rule:
    name: Allow ICMPv4-In
    protocol: icmpv4
    action: allow
    direction: in
    enabled: yes
    state: present

- name: Ensure Firewall allows RDP and WinRM
  ansible.windows.win_shell: |
    Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    Enable-NetFirewallRule -DisplayGroup "Windows Remote Management"
  ignore_errors: true

- name: Change Windows User Password
  ansible.windows.win_user:
    name: windows
    password: "qwerty!23"
    state: present
    password_never_expires: yes
    update_password: always
